### PR TITLE
Fix broken Url in SPEC_DRAFT.md

### PR DESCRIPTION
**Pull request by evantill**
- Fix broken url to the *The Kubernetes Resource Model* : The kubernetes design proposals section was moved to an archived repository.

### CODE REVIEW

**Comment by zt810950783** [comment]
邮件已收到，谢谢

**Review by wonderflow — APPROVED** [review]

**Comment by zt810950783** [comment]
邮件已收到，谢谢

**Comment by evantill** [comment]
Thank you

**Comment by zeusro** [comment]
Good job,  @wonderflow

**Pull request merged**
