### PR TITLE
readme edit

### PR DESCRIPTION
**Pull request by rbitia**
Focusing on OSS projects

### CODE REVIEW

**Comment by technosophos** [comment]
Why are we removing this? They did actually contribute to the spec, and Service Fabric is an open source project.

**Comment by rbitia** [comment]
I agree but I don't think that's something folks reading the repo should first see or get held up on. Maybe we can move this line to another file?

**Comment by vturecek** [comment]
Hm, seems weird to not mention other projects that contributors have worked on just because those projects don't meet some standard of open source (SF technically is open source, even though it's not developed openly). I think SF is very relevant to the distributed applications space of this spec, open source or not. I don't think we should merge this change.

**Comment by rbitia** [comment]
I made a fix can you go off that? I don't think you need to mention who the creators are in the first paragraph. I think they are better suited for the collaboration section.

**Comment by resouer** [comment]
Ah, this is interesting. I just got a feedback immediately after we shared the link to one partner that this line "is not community friendly". I think the main reason is we list it as the first line of the README of spec.

I will +1 for Ria.

**Comment by technosophos** [comment]
I am okay with moving to the bottom, or even deleting the entire sentence.

**Comment by hongchaodeng** [comment]
Well, a hero mention little about his past glories.

Let's delete the line and focus on the making OAM the next great community project :)

**Comment by technosophos** [comment]
@rbitia Would you be okay just removing that entire sentence? I think we're all starting to question its value now.

**Comment by rbitia** [comment]
Yeah I'm cool with that too! I can push up another fix

**Comment by suhuruli** [comment]
I am cool with this change (Y)

**Comment by vturecek** [comment]
Removing it entirely sounds better to me than just removing one.

**Pull request merged**
