### PR TITLE
Don't require a leading dot for JSON field paths

### PR DESCRIPTION
**Pull request by negz**
https://github.com/kubernetes/community/blob/ddc11a7/contributors/devel/sig-architecture/api-conventions.md#selecting-fields

This allows us to leverage existing libraries and patterns designed for Kubernetes field paths, per https://github.com/crossplane/crossplane-runtime/issues/136.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Ref https://github.com/oam-dev/spec/pull/335

If this is a written k8s convention, we should follow and add a line in the spec. Also need to update examples and design doc.

**Comment by negz** [comment]
Ping. Does this seem uncontroversial enough to merge?

**Comment by resouer** [comment]
/lgtm

This one is good enough to merge. Thorough fix could be done by follow up PRs.

**Comment by hongchaodeng** [comment]
@hasheddan 
Note that this is NOT merged into master branch.
Just combine this commit in your follow up PRs.

**Pull request merged**
