### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by pmorie**
:)

### CODE REVIEW

**Review by resouer — APPROVED** [review]
LGTM, Thanks Paul, will merge after CLA signed.

**Comment by pmorie** [comment]
Thanks, working on CLA on my side now.

**Comment by pmorie** [comment]
I have to get some updated guidance from our legal team on how they want me to sign the CLA. I've made a ticket and should know more soon.

**Comment by resouer** [comment]
@pmorie Thanks Paul. It's totally understandable.

**Pull request merged**
