### PR TITLE
add link to google calendar

### PR DESCRIPTION
**Pull request by suhuruli**

### CODE REVIEW

**Comment by suhuruli** [comment]
@tomkerkhove , this should be fixed now. Let me know!

**Comment by tomkerkhove** [comment]
Works fine, thanks!

**Comment by vturecek** [comment]
Is this a general calendar for our google group, or is the link just adding an event to my google calendar?

**Comment by vturecek** [comment]
OK, seems fine, but is there a way to create a shared calendar for the group?

**Comment by suhuruli** [comment]
What do you mean shared calendar? What this does is it adds the OAM Community Calendar to a user's Google account so they can see when OAM community events are held. I suggest we merge this small change and take the discussions to Gitter.

**Pull request merged**
