### PR TITLE
setup i18n framework

### PR DESCRIPTION
**Pull request by wonderflow**
Now I have setup a framework for Chinese Translation. I think we could work together and split the work.

\cc @KaiwenWang @captainroy-hy @resouer 

refs #258 #233

### CODE REVIEW

**Comment by vturecek** [comment]
Thanks for getting this started, the framework looks good. What do you think about doing the translation in a separate branch for now, until we have an initial translation of each section? Would that make the process a bit easier so we can get translation PRs merged faster without disrupting master during the process?

**Comment by wonderflow** [comment]
@vturecek  yeah，I'm okay. But could we have some reference in the master branch?

**Comment by wonderflow** [comment]
@hongchaodeng please help create a i18n branch.

**Comment by hongchaodeng** [comment]
Created `i18n` branch:

https://github.com/oam-dev/spec/tree/i18n

Just submit pull request targeted to that

**Comment by wonderflow** [comment]
I have open a new PR to `i18n` branch. 

Closing this one..

**Pull request closed without merging**
